package droolsRules;

import com.leFinance.creditLoan.bizRule.fact.ContractFact;

dialect  "mvel"

/**
 * created by zhulili1, on 2017/10/1
 * @Description: 创建融资担保委托合同业务规则
 **/

// 创建融资担保委托合同
rule "create garantee contract"
    lock-on-active
    when
        $b : ContractFact(feeValue != null)
    then
        $b.setCreateDBContract(true);
end

// 不创建融资担保委托合同
rule "not create garantee contract"
    lock-on-active
when
        $b : ContractFact(feeValue == null)
    then
        $b.setCreateDBContract(false);
end